print("Fantastic 4 Movie Script")
print("Our first thought: DR. DOOM?  But it's not moving.  A")
print("welder's torch sparks into frame in the hands of a sculptor")
print("on scaffolding.  This is art, an epic 20 foot statue going up")
print("of a business mogul (VICTOR VON DOOM) in whose generously")
print("extended hands sit two intertwined columns of DNA.  His face")
print("is chiseled, angular, perfect (too perfect).  Past sparks, we")
print("MOVE down to pick up...")
print("")
print("EXT. STREET/VON DOOM INDUSTRIES TOWER - DAY")
print("REED RICHARDS and BEN GRIMM head toward the soaring glass-box")
print("atrium of VDI Headquarters.  Designed to inspire awe, it")
print("does.")
print("")
print("")
print("                     REED")
print("High open space, exposed structural")
print("elements.  Obviously aimed at first")
print("time visitors to create feelings of...")
print("smallness, inadequacy.")
print("")
print("Ben glances at Reed, who looks a little nervous.")
print("")
print("BEN")
print("Good thing it ain't workin... Reed,")
print("what are we doing here?  This guy's")
print("fast-food, strip-mall science --")
print("           REED")
print("This wasn't our first stop, in case")
print("you forgot NASA.  And Victor's not")
print("that bad.  He's just a little...")
print("    (seeing the statue)")
print("Larger than life.")
print("")
print("INT. VON DOOM INDUSTRIES TOWER - DAY")
print("")
print("They move past the statue, into the sprawling atrium.")
print("")
print("                REED")
print("      He's financed some of the biggest")
print("      breakthroughs of this century.")
print("")
print("             BEN")
print("     You'd never know it.")